name: Matrix Demo
on: push

jobs:
  build:
    strategy:
      matrix:
        # combinations of node-versions and OS will run parallelly
        node-version: [12, 14, 16]
        operating-system: [ubuntu-latest, windows-latest]
    # ubuntu-latest and windows-latest will run in parallel
    runs-on: ${{ matrix.operating-system }}
    steps:
      - name: Get Code
        uses: actions/checkout@v3
      - name: Install NodeJS
        uses: actions/setup-node@v3
        with:
          nonde-version: ${{ matrix.node-version }}
      - name: Install Dependencies
        run: npm ci
      - name: Build project
        run: npm run build        
